# Generated by Django 3.1.2 on 2020-10-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_walking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='walking',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='walking',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
