# Generated by Django 3.1.2 on 2020-10-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_dog_toys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toy',
            name='type',
        ),
    ]
